### ISSUE TITLE
broken links in README

### ISSUE THREAD

**Issue by beenotung** [krixano/Lydrige#9]
The links in README file and project page (github) are broken.
For example https://www.krixano.x10host.com/projects/Lydrige/Docs
Display "Sorry, the page you are looking for could not be found."

**Comment by krixano** [comment]
Yeah, sorry. I've replaced my main website with a different one so that I could host it for a project for university. Once I get a different site setup for it, I'll put my main website back, which will fix the links.

**Comment by krixano** [comment]
This should be fixed now.
